### ISSUE TITLE
Errors which block deployment

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#13]
Creating globalblocks table ...A database query error has occurred.
Query: CREATE TABLE `global_block_whitelist` (
 gbw_id int(11) NOT NULL PRIMARY KEY, -- Key to gb_id in globalblocks database.
 gbw_address varbinary(255) NOT NULL,
 gbw_by int(11) NOT NULL, -- Key to user_id
 gbw_by_text varchar(255) NOT NULL,
 gbw_reason varchar(255) NOT NULL,
 gbw_expiry binary(14) NOT NULL
 ) ENGINE=InnoDB

Function: DatabaseBase::sourceFile( /srv/mediawiki/w/extensions/GlobalBlocking/includes/../globalblocking.sql )
Error: 1050 Table 'global_block_whitelist' already exists (185.52.1.77)

**Comment by Southparkfan** [comment]
This one too:

SQL ERROR: DROP command denied to user 'mediawiki'@'185.52.1.75' for table 'translate_tms' (185.52.1.77)
[Bug56269] Exception thrown with an uncommited database transaction: [ce6c6a07] /wiki/Special:CreateWiki   DBQuery
Error from line 1246 of /srv/mediawiki/w/includes/db/Database.php: A database error has occurred. Did you forget t
o run maintenance/update.php after upgrading?  See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update
_script
Query: DROP TABLE IF EXISTS `translate_tms`

Function: DatabaseBase::sourceFile( /srv/mediawiki/w/extensions/Translate/sql/translate_tm.sql )
Error: 1142 DROP command denied to user 'mediawiki'@'185.52.1.75' for table 'translate_tms' (185.52.1.77)

#0 /srv/mediawiki/w/includes/db/Database.php(1205): DatabaseBase->reportQueryError()
#1 /srv/mediawiki/w/includes/db/Database.php(4090): DatabaseBase->query()
#2 /srv/mediawiki/w/includes/db/Database.php(4004): DatabaseBase->sourceStream()
#3 /srv/mediawiki/w/extensions/CreateWiki/SpecialCreateWiki.php(92): DatabaseBase->sourceFile()
#4 /srv/mediawiki/w/extensions/CreateWiki/SpecialCreateWiki.php(15): SpecialCreateWiki->handleInput()
#5 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(384): SpecialCreateWiki->execute()
#6 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run()
#7 /srv/mediawiki/w/includes/MediaWiki.php(267): SpecialPageFactory::executePath()
#8 /srv/mediawiki/w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#9 /srv/mediawiki/w/includes/MediaWiki.php(414): MediaWiki->main()
#10 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#11 {main}
OutputPage::sendCacheControl: no caching **
[error] [8fcc1148] /wiki/Special:CreateWiki   ErrorException from line 4362 of /srv/mediawiki/w/includes/db/Databa
se.php: PHP Notice: Uncommitted DB writes (transaction from DatabaseBase::query (LCStoreDB::get)).
#0 (): MWExceptionHandler::handleError()
#1 /srv/mediawiki/w/includes/db/Database.php(4362): trigger_error()
#2 (): DatabaseBase->__destruct()
#3 {main}

**Comment by Southparkfan** [comment]
Fixed.
