### ISSUE TITLE
ErrorException from line 418 of /srv/mediawiki/w/includes/diff/DairikiDiff.php: PHP Notice: Undefined property: DiffEngine::$seq

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#193]
```
2015-10-18 08:20:05 mw1 spiralwiki: [a675db15] /w/index.php?title=Happiness_for_everyone&diff=prev&oldid=668   ErrorException from line 418 of /srv/mediawiki/w/includes/diff/DairikiDiff.php: PHP Notice: Undefined property: DiffEngine::$seq
#0 /srv/mediawiki/w/includes/diff/DairikiDiff.php(418): MWExceptionHandler::handleError()
#1 /srv/mediawiki/w/includes/diff/DairikiDiff.php(544): DiffEngine->diag()
#2 /srv/mediawiki/w/includes/diff/DairikiDiff.php(344): DiffEngine->compareSeq()
#3 /srv/mediawiki/w/includes/diff/DairikiDiff.php(227): DiffEngine->diffLocal()
#4 /srv/mediawiki/w/includes/diff/DairikiDiff.php(721): DiffEngine->diff()
#5 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(886): Diff->__construct()
#6 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(802): DifferenceEngine->generateTextDiffBody()
#7 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(733): DifferenceEngine->generateContentDiffBody()
#8 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(662): DifferenceEngine->getDiffBody()
#9 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(632): DifferenceEngine->getDiff()
#10 /srv/mediawiki/w/includes/diff/DifferenceEngine.php(453): DifferenceEngine->showDiff()
#11 /srv/mediawiki/w/includes/page/Article.php(795): DifferenceEngine->showDiffPage()
#12 /srv/mediawiki/w/includes/page/Article.php(506): Article->showDiffPage()
#13 /srv/mediawiki/w/includes/actions/ViewAction.php(44): Article->view()
#14 /srv/mediawiki/w/includes/MediaWiki.php(395): ViewAction->show()
#15 /srv/mediawiki/w/includes/MediaWiki.php(273): MediaWiki->performAction()
#16 /srv/mediawiki/w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#17 /srv/mediawiki/w/includes/MediaWiki.php(414): MediaWiki->main()
#18 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#19 {main}
```
Need to take a look at this.

**Comment by Southparkfan** [comment]
Not able to reproduce.

**Comment by Southparkfan** [comment]
Actually, this bug was fixed upstream: https://phabricator.wikimedia.org/T116266

**Comment by Southparkfan** [comment]
I need to backport the patch, I guess.

**Comment by Southparkfan** [comment]
Upstream backported the patch to REL1_26. Git pulled from upstream, fixed.
