### ISSUE TITLE
 MWException from line 111 of /srv/mediawiki/w/includes/page/WikiPage.php: Invalid or virtual namespace -1 given

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#194]
```
[Bug56269] Exception thrown with an uncommited database transaction: [4da18c4d] /w/index.php?title=Special:NewMessages&action=submit   MWException from line 111 of /srv/mediawiki/w/includes/page/WikiPage.php: Invalid or virtual namespace -1 given.
#0 /srv/mediawiki/w/includes/context/RequestContext.php(228): WikiPage::factory()
#1 /srv/mediawiki/w/extensions/SpamBlacklist/SpamBlacklistHooks.php(52): RequestContext->getWikiPage()
#2 /srv/mediawiki/w/includes/Hooks.php(209): SpamBlacklistHooks::filterMergedContent()
#3 /srv/mediawiki/w/includes/EditPage.php(1450): Hooks::run()
#4 /srv/mediawiki/w/includes/EditPage.php(1720): EditPage->runPostMergeFilters()
#5 /srv/mediawiki/w/includes/EditPage.php(1305): EditPage->internalAttemptSave()
#6 /srv/mediawiki/w/includes/EditPage.php(539): EditPage->attemptSave()
#7 /srv/mediawiki/w/extensions/LiquidThreads/classes/View.php(664): EditPage->edit()
#8 /srv/mediawiki/w/extensions/LiquidThreads/classes/View.php(2193): LqtView->showReplyForm()
#9 /srv/mediawiki/w/extensions/LiquidThreads/pages/NewUserMessagesView.php(184): LqtView->showThread()
#10 /srv/mediawiki/w/extensions/LiquidThreads/pages/NewUserMessagesView.php(134): NewUserMessagesView->showWrappedThread()
#11 /srv/mediawiki/w/extensions/LiquidThreads/pages/SpecialNewMessages.php(39): NewUserMessagesView->show()
#12 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(384): SpecialNewMessages->execute()
#13 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run()
#14 /srv/mediawiki/w/includes/MediaWiki.php(267): SpecialPageFactory::executePath()
#15 /srv/mediawiki/w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#16 /srv/mediawiki/w/includes/MediaWiki.php(414): MediaWiki->main()
#17 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#18 {main}
```

**Comment by Reception123** [comment]
To be filed on Phabricator.

**Comment by Reception123** [comment]
I got this response from Ciencia Al Poder on mediawiki.org "Apparently, the SpamBlacklist extension doesn't work when editing LQT posts in Special:NewMessages? Try disabling that extension and see if it works. May be worth filing a bug report on phabricator."

**Comment by JohnFLewis** [comment]
Sounds like a Kill LQT sub-issue. So closing for #416
