### ISSUE TITLE
Cannot access CentralAuth

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#216]
```Exception encountered, of type "Exception"```

**Comment by Southparkfan** [comment]
```
2015-12-14 15:51:17 mw1 metawiki: [955fa3cd] /w/index.php?title=Special%3ACentralAuth&target=Revi   Exception from line 2110 of /srv/mediawiki/w/extensions/CentralAuth/includes/CentralAuthUser.php: Could not find local user data for Revi@welcomewikiwiki
#0 /srv/mediawiki/w/extensions/CentralAuth/includes/CentralAuthUser.php(2050): CentralAuthUser->localUserData()
#1 /srv/mediawiki/w/extensions/CentralAuth/includes/specials/SpecialCentralAuth.php(94): CentralAuthUser->queryAttached()
#2 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(384): SpecialCentralAuth->execute()
#3 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run()
#4 /srv/mediawiki/w/includes/MediaWiki.php(267): SpecialPageFactory::executePath()
#5 /srv/mediawiki/w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#6 /srv/mediawiki/w/includes/MediaWiki.php(414): MediaWiki->main()
#7 /srv/mediawiki/w/index.php(41): MediaWiki->run()
```

Fixed it with root@mw1:/srv/mediawiki/w/extensions/CentralAuth/maintenance# php createLocalAccount.php --wiki welcomewikiwiki Revi.
