### ISSUE TITLE
/wiki/Special:RecentChanges ErrorException from line 300 of /srv/mediawiki/w/includes/debug/MWDebug.php: PHP Warning: OutputPage::getModuleStyles: style module should define its position explicitly: ext.tabs ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /srv/mediawiki/w/includes/OutputPage.php at line 623]

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#258]
Happening since the 1.26 upgrade:
```
2015-12-29 20:09:19 mw1 allthetropeswiki: [20ca0905] /wiki/Special:RecentChanges   ErrorException from line 300 of /srv/mediawiki/w/includes/debug/MWDebug.php: PHP Warning: OutputPage::getModuleStyles: style module should define its position explicitly: ext.tabs ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /srv/mediawiki/w/includes/OutputPage.php at line 623]
#0 /srv/mediawiki/w/includes/debug/MWDebug.php(300): MWExceptionHandler::handleError(integer, string, string, integer, array, array)
#1 /srv/mediawiki/w/includes/debug/MWDebug.php(155): MWDebug::sendMessage(string, array, string, integer)
#2 /srv/mediawiki/w/includes/GlobalFunctions.php(1222): MWDebug::warning(string, integer, integer, string)
#3 /srv/mediawiki/w/includes/OutputPage.php(623): wfLogWarning(string)
#4 /srv/mediawiki/w/includes/OutputPage.php(3668): OutputPage->getModuleStyles(boolean, string)
#5 /srv/mediawiki/w/includes/OutputPage.php(2714): OutputPage->buildCssLinks()
#6 /srv/mediawiki/w/includes/skins/SkinTemplate.php(465): OutputPage->headElement(SkinVector)
#7 /srv/mediawiki/w/includes/skins/SkinTemplate.php(240): SkinTemplate->prepareQuickTemplate(OutputPage)
#8 /srv/mediawiki/w/includes/OutputPage.php(2326): SkinTemplate->outputPage()
#9 /srv/mediawiki/w/includes/MediaWiki.php(722): OutputPage->output()
#10 /srv/mediawiki/w/includes/MediaWiki.php(508): MediaWiki->main()
#11 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#12 {main}
```

**Comment by Southparkfan** [comment]
Fixes merged upstream: https://gerrit.wikimedia.org/r/#/q/I532503ad3a41f1a0e7a31b23289506b6b7019b8a,n,z

Pending merge by jenkins-bot I guess.

**Comment by Southparkfan** [comment]
Need to pull this change into the mediawiki repo.

**Comment by Southparkfan** [comment]
Pulled and fixed.
