### ISSUE TITLE
DevelopmentWiki Exception encountered, of type "BadMethodCallException"

### ISSUE THREAD

**Issue by NDKilla-public** [miraheze/mw-config#263]
This error shows up sporadically (sometimes, not all the time. Probably less often than showing up) on development.miraheze.org. Noticed mainly on [Special:RecentChanges](https://development.miraheze.org/wiki/Special:RecentChanges)

12:01:35 PM <+SPF|Cloud> 2015-12-30 16:57:22 mw1 developmentwiki: [ddc31cd5] /wiki/Special:RecentChanges   BadMethodCallException from line 499 of /srv/mediawiki/w/includes/changes/EnhancedChangesList.php: Call to a member function getTitle() on a non-object (NULL)

**Comment by Southparkfan** [comment]
```
2015-12-28 19:34:51 mw1 developmentwiki: [b588a979] /wiki/Special:RecentChanges   BadMethodCallException from line 499 of /srv/mediawiki/w/includes/changes/EnhancedChangesList.php: Call to a member function getTitle() on a non-object (NULL)
#0 /srv/mediawiki/w/includes/changes/EnhancedChangesList.php(287): EnhancedChangesList->getLogText(array, array, boolean, boolean, boolean)
#1 /srv/mediawiki/w/includes/changes/EnhancedChangesList.php(683): EnhancedChangesList->recentChangesBlockGroup(array)
#2 /srv/mediawiki/w/includes/changes/EnhancedChangesList.php(103): EnhancedChangesList->recentChangesBlock()
#3 /srv/mediawiki/w/includes/specials/SpecialRecentchanges.php(356): EnhancedChangesList->recentChangesLine(RecentChange, boolean, integer)
#4 /srv/mediawiki/w/includes/specialpage/ChangesListSpecialPage.php(348): SpecialRecentChanges->outputChangesList(ResultWrapper, FormOptions)
#5 /srv/mediawiki/w/includes/specialpage/ChangesListSpecialPage.php(77): ChangesListSpecialPage->webOutput(ResultWrapper, FormOptions)
#6 /srv/mediawiki/w/includes/specials/SpecialRecentchanges.php(64): ChangesListSpecialPage->execute(NULL)
#7 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(384): SpecialRecentChanges->execute(NULL)
#8 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(NULL)
#9 /srv/mediawiki/w/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#10 /srv/mediawiki/w/includes/MediaWiki.php(714): MediaWiki->performRequest()
#11 /srv/mediawiki/w/includes/MediaWiki.php(508): MediaWiki->main()
#12 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#13 {main}
```

**Comment by Reception123** [comment]
I'm also getting it while logged-in to my account now. (Before it worked fine)

**Comment by NDKilla** [comment]
Fixed? Haven't been seeing it logged in or out.
