### ISSUE TITLE
Exception from line 2114 of /srv/mediawiki/w/extensions/CentralAuth/includes/CentralAuthUser.php: Could not find local user data for AnalisaFulford@spiralwiki

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#264]
```
2015-12-30 17:04:36 mw1 printmakingbewiki: [c1c4074f] /wiki/Special:CentralAuth/AnalisaFulford   Exception from line 2114 of /srv/mediawiki/w/extensions/CentralAuth/includes/CentralAuthUser.php: Could not find local user data for AnalisaFulford@spiralwiki
#0 /srv/mediawiki/w/extensions/CentralAuth/includes/CentralAuthUser.php(2054): CentralAuthUser->localUserData(string)
#1 /srv/mediawiki/w/extensions/CentralAuth/includes/specials/SpecialCentralAuth.php(96): CentralAuthUser->queryAttached()
#2 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(384): SpecialCentralAuth->execute(string)
#3 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(string)
#4 /srv/mediawiki/w/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#5 /srv/mediawiki/w/includes/MediaWiki.php(714): MediaWiki->performRequest()
#6 /srv/mediawiki/w/includes/MediaWiki.php(508): MediaWiki->main()
#7 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#8 {main}
```

Affects WMF too: https://phabricator.wikimedia.org/T119736
We might want to backport their 'patches'.

**Comment by Southparkfan** [comment]
And run checkLocalUser.php.

**Comment by Southparkfan** [comment]
```
root@mw1:/var/log/mediawiki/debuglogs# zgrep 'Could not find local user data for ' exception.log.*.gz | wc -l
1672
root@mw1:/var/log/mediawiki/debuglogs# zgrep 'Could not find local user data for ' exception.log.*.gz | grep -v spiralwiki | wc -l
16
```

For some reason almost all entries are for users at spiralwiki.

**Comment by Southparkfan** [comment]
I deleted wrong entries using checkLocalUser.php --delete and checkLocalNames.php --delete. All missing entries were @ spiralwiki. https://phabricator.wikimedia.org/T115198#1948271

**Comment by Southparkfan** [comment]
Seems to be back:
```
Checking localuser for metawiki ...
2016-03-10 16:57:19 found 46 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for anuwiki ...
2016-03-10 16:57:27 found 4 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for allthetropeswiki ...
2016-03-10 16:57:36 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for partupwiki ...
2016-03-10 16:58:04 found 2 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for fantasticfourwiki ...
2016-03-10 16:58:51 found 5 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for scheerswiki ...
2016-03-10 16:59:01 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for solwiki ...
2016-03-10 16:59:08 found 2 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for bdorpwiki ...
2016-03-10 16:59:10 found 6 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for lbsgeswiki ...
2016-03-10 16:59:14 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for santrovelowiki ...
2016-03-10 16:59:15 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for seldirwiki ...
2016-03-10 16:59:18 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for lclwikiwiki ...
2016-03-10 16:59:20 found 7 invalid localuser, 0 (0.0%) deleted
Checking localuser for railroverwiki ...
2016-03-10 16:59:20 found 1 invalid localuser, 0 (0.0%) deleted
--
Checking localuser for hftqmswiki ...
2016-03-10 16:59:25 found 1 invalid localuser, 0 (0.0%) deleted
```
https://meta.miraheze.org/wiki/Stewards'_noticeboard#Impossible_to_create_account

**Comment by labster** [comment]
They closed your ticket as a dupe of https://phabricator.wikimedia.org/T119736

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T145.
