### ISSUE TITLE
ErrorException from line 105 of /srv/mediawiki/w/includes/page/WikiPage.php: PHP Error: Argument 1 passed to WikiPage::factory() must be an instance of Title, null given

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#276]
```
2016-01-07 16:08:52 mw1 poserdazfreebiestestwiki: [46c0d3d6] [no req]   ErrorException from line 105 of /srv/mediawiki/w/includes/page/WikiPage.php: PHP Error: Argument 1 passed to WikiPage::factory() must be an instance of Title, null given, called in /srv/mediawiki/w/includes/Import.php on line 386 and defined
#0 /srv/mediawiki/w/includes/page/WikiPage.php(105): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/mediawiki/w/includes/Import.php(386): WikiPage::factory(NULL)
#2 [internal function]: WikiImporter->finishImportPage(NULL, NULL, integer, integer, array)
#3 /srv/mediawiki/w/includes/Import.php(461): call_user_func_array(array, array)
#4 /srv/mediawiki/w/includes/Import.php(756): WikiImporter->pageOutCallback(NULL, NULL, integer, integer, array)
#5 /srv/mediawiki/w/includes/Import.php(566): WikiImporter->handlePage()
#6 /srv/mediawiki/w/maintenance/importDump.php(299): WikiImporter->doImport()
#7 /srv/mediawiki/w/maintenance/importDump.php(257): BackupReader->importFromHandle(resource)
#8 /srv/mediawiki/w/maintenance/importDump.php(102): BackupReader->importFromFile(string)
#9 /srv/mediawiki/w/maintenance/doMaintenance.php(103): BackupReader->execute()
#10 /srv/mediawiki/w/maintenance/importDump.php(304): require_once(string)
#11 {main}
```
Blocks import of /root/poserdazfreebiesorainorg_w-20150808-history.xml.

**Comment by Southparkfan** [comment]
Task filed: https://phabricator.wikimedia.org/T123075

**Comment by Southparkfan** [comment]
Fixed in REL1_26.
