### ISSUE TITLE
ErrorException from line 80 of /srv/mediawiki/w/extensions/LiquidThreads/pages/ThreadPermalinkView.php: PHP Notice: Undefined offset: 110

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#316]
```
2016-01-25 17:07:13 mw1 allthetropeswiki: [52ead63a] /wiki/Thread:Forum:Page_Images/A_Date_with_Rosie_Palms/reply_(3)   ErrorException from line 80 of /srv/mediawiki/w/extensions/LiquidThreads/pages/ThreadPermalinkView.php: PHP Notice: Undefined offset: 110
#0 /srv/mediawiki/w/extensions/LiquidThreads/pages/ThreadPermalinkView.php(80): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/mediawiki/w/extensions/LiquidThreads/pages/ThreadPermalinkView.php(25): ThreadPermalinkView::getCustomTabs(ThreadPermalinkView)
#2 /srv/mediawiki/w/extensions/LiquidThreads/pages/ThreadPermalinkView.php(7): ThreadPermalinkView::customizeThreadNavigation(SkinVector, array, ThreadPermalinkView)
#3 /srv/mediawiki/w/extensions/LiquidThreads/classes/Dispatch.php(234): ThreadPermalinkView->customizeNavigation(SkinVector, array)
#4 [internal function]: LqtDispatch::onSkinTemplateNavigation(SkinVector, array)
#5 /srv/mediawiki/w/includes/Hooks.php(201): call_user_func_array(string, array)
#6 /srv/mediawiki/w/includes/skins/SkinTemplate.php(1032): Hooks::run(string, array)
#7 /srv/mediawiki/w/includes/skins/SkinTemplate.php(456): SkinTemplate->buildContentNavigationUrls()
#8 /srv/mediawiki/w/includes/skins/SkinTemplate.php(240): SkinTemplate->prepareQuickTemplate(OutputPage)
#9 /srv/mediawiki/w/includes/OutputPage.php(2326): SkinTemplate->outputPage()
#10 /srv/mediawiki/w/includes/MediaWiki.php(722): OutputPage->output()
#11 /srv/mediawiki/w/includes/MediaWiki.php(508): MediaWiki->main()
#12 /srv/mediawiki/w/index.php(41): MediaWiki->run()
#13 {main}
```

**Comment by JohnFLewis** [comment]
Should be titled "Get rid of LQT" but whatever

**Comment by NDKilla** [comment]
^ +1
needs more flow

**Comment by JohnFLewis** [comment]
Closing for the above. Let's not fix it, let's kill it.
